### ISSUE TITLE
declare tick or

### ISSUE THREAD

**Issue by GDmac** [ackintosh/snidel#36]
https://github.com/ackintosh/snidel/blob/master/src/Snidel/Fork/Coordinator.php#L152
(From my comment at BernardPHP)
Declare tick should maybe not be used at all, many places on the web it is suggested  to use [pcntl_signal_dispatch](http://php.net/manual/en/function.pcntl-signal-dispatch.php) instead.  
Inside the drivers, instead of usleep(), could use [time_nanosleep](http://php.net/manual/en/function.time-nanosleep.php), which is interruptable.  

```php
pcntl_signal_dispatch();
$nano = time_nanosleep(0, 100000000);
if ($nano === true) {
  // slept
} elseif ($nano === false) {
  // nanosleep fail
  usleep(100000);
} elseif (is_array($nano)) {
  // Interrupted by a signal
  pcntl_signal_dispatch();
  return array(null, null);
}
pcntl_signal_dispatch();
```
(edit: via https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/125 )

**Comment by ackintosh** [comment]
Hi @GDmac , thanks for letting me know about that! ✨ 

I'll update with pcntl_signal_dispatch according to your comment. Please let me know if you would like to address the improvement.

**Comment by GDmac** [comment]
Nice, however beware, 
you have not added the fail-safe,
in case nano-sleep returns false ?
